---
title: "Project pike"
author: "TR"
date: '2022-09-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(ggplot2)
library(lme4)
library(nlme)
library(lmerTest)
library(emmeans)
library(MuMIn)
library(visreg)
library(car)
library(sjPlot)
library(knitr)
library(car)
library(ggpubr)
library(mclust)
library(dtwclust)
library(vegan)
library(mvabund)
library(MASS)
```

## preparation of Sr and d18O data
```{r marry d18O data to Sr, include=FALSE, eval=FALSE}
#Read in LA-ICPMS and SIMS data
rm(list = ls())

LA <- read.delim("Data/Pike/pike_data_LA-ICPMS_years_with_core.txt", 
                 header = T, stringsAsFactors = F, sep = "\t", dec = ".")

d18O <- read.delim("Data/Pike/pike_data_d18O_years.txt", header = T,
                stringsAsFactors = F, sep = "\t", dec = ".")

#Clean up data & assign capture locations to main areas
#Trace element data
LA <- LA%>%
  filter(LA_dist>=50)%>%
  transmute(ID = ID,
            age=age,
            capt = area,
            area = case_when(area %in% "Peene" ~ "Freshwater",
                             area %in% "Barthe" ~ "Freshwater",
                             area %in% "NHG" ~ "Freshwater",
                             area %in% "Sehrowbach" ~ "Freshwater",
                             area %in% "Bandycksgraben" ~ "Freshwater",
                             area %in% "Ziese" ~ "Freshwater",
                             area %in% "KB" ~ "WRB",
                             area %in% "SB" ~ "WRB",
                             area %in% "WB" ~ "NRB",
                             area %in% "BEG" ~ "NRB", 
                             area %in% "KJB" ~ "NRB",
                             area %in% "GJB" ~ "NRB",
                             area %in% "GB" ~ "GB",
                             area %in% "KD" ~ "control",
                             TRUE ~ "NA"),
            Sr = Sr,
            Na = Na,
            Mg = Mg,
            Ba = Ba,
            Mn = Mn,
            LA_dist = LA_dist,
            year=year)

#d18O data
d18O <- d18O%>%
  transmute(ID = ID,
            age=age,
            capt = area,
            area = case_when(area %in% "Peene" ~ "Freshwater",
                             area %in% "Barthe" ~ "Freshwater",
                             area %in% "NHG" ~ "Freshwater",
                             area %in% "Sehrowbach" ~ "Freshwater",
                             area %in% "Bandycksgraben" ~ "Freshwater",
                             area %in% "Ziese" ~ "Freshwater",
                             area %in% "KB" ~ "WRB",
                             area %in% "SB" ~ "WRB",
                             area %in% "WB" ~ "NRB",
                             area %in% "BEG" ~ "NRB", 
                             area %in% "KJB" ~ "NRB",
                             area %in% "GJB" ~ "NRB",
                             area %in% "GB" ~ "Marine",
                             area %in% "KD" ~ "Control",
                             TRUE ~ "NA"),
            d18O = d18O,
            sims_dist = sims_dist,
            year=year)

LA <- LA %>% drop_na()

#Smooth trace element data to get rid of extreme values
LA_smooth <- LA%>%group_by(ID)%>%
  transmute(ID=ID,
            age=age,
            capt=capt,
            area=area,
            Sr=as.numeric(zoo::rollmean(Sr, k=9, fill=NA, align = "left")),
            Na=as.numeric(zoo::rollmean(Na, k=9, fill=NA, align = "left")),
            Mg=as.numeric(zoo::rollmean(Mg, k=9, fill=NA, align = "left")),
            Ba=as.numeric(zoo::rollmean(Ba, k=9, fill=NA, align = "left")),
            Mn=as.numeric(zoo::rollmean(Mn, k=9, fill=NA, align = "left")),
            LA_dist=as.numeric(LA_dist),
            year=year)

#Order data for joining
d18O <- d18O[order(d18O$ID),]
LA <- LA[order(LA$ID),]
LA_smooth <- LA_smooth[order(LA_smooth$ID),]
LA_smooth <- data.frame(LA_smooth)

#reinterpolate Sr (higher spatial resolution) to d18O distances (lower spatial resolution) for joining
IDOto <- unique(d18O$ID)
dfE <- data.frame()
for (i in 1:length(IDOto)) {
  Sr <- data.frame(approx(LA_smooth[which(LA_smooth$ID==IDOto[i]),"LA_dist"],
              LA_smooth[which(LA_smooth$ID==IDOto[i]),"Sr"],
              n = length(d18O[which(d18O$ID==IDOto[i]),"sims_dist"]),
              rule = 1, method = "linear", ties = "ordered"))
  Na <- data.frame(approx(LA_smooth[which(LA_smooth$ID==IDOto[i]),"LA_dist"],
              LA_smooth[which(LA_smooth$ID==IDOto[i]),"Na"],
              n = length(d18O[which(d18O$ID==IDOto[i]),"sims_dist"]),
              rule = 1, method = "linear", ties = "ordered"))
  Mg <- data.frame(approx(LA_smooth[which(LA_smooth$ID==IDOto[i]),"LA_dist"],
              LA_smooth[which(LA_smooth$ID==IDOto[i]),"Mg"],
              n = length(d18O[which(d18O$ID==IDOto[i]),"sims_dist"]),
              rule = 1, method = "linear", ties = "ordered"))
  Ba <- data.frame(approx(LA_smooth[which(LA_smooth$ID==IDOto[i]),"LA_dist"],
              LA_smooth[which(LA_smooth$ID==IDOto[i]),"Ba"],
              n = length(d18O[which(d18O$ID==IDOto[i]),"sims_dist"]),
              rule = 1, method = "linear", ties = "ordered"))
  Mn <- data.frame(approx(LA_smooth[which(LA_smooth$ID==IDOto[i]),"LA_dist"],
              LA_smooth[which(LA_smooth$ID==IDOto[i]),"Mn"],
              n = length(d18O[which(d18O$ID==IDOto[i]),"sims_dist"]),
              rule = 1, method = "linear", ties = "ordered"))
  df <- cbind(Sr=Sr[,2], Na=Na[,2], Mg=Mg[,2], Ba=Ba[,2], Mn=Mn[,2])
  dfE <- rbind(dfE,df)
}

otoint_lowres <- cbind(d18O, dfE)
```

```{r covariance d18O and Sr, include=FALSE, eval=FALSE}
#clean up
Oto_lowres <- otoint_lowres%>%
  filter(capt!="KD")%>%
  filter(ID!="BH-01908")%>%
  transmute(ID=ID,
            capt=capt,
            area=area,
            dist=dist,
            Sr=Sr,
            d18O=d18O)%>%
  drop_na()

#plot high signal fish
Testfish1 <- Oto_lowres%>%filter(ID=="BH-90946")
Testfish2 <- Oto_lowres%>%filter(ID=="BH-91050")
Testfish3 <- Oto_lowres%>%filter(ID=="BH-90928")
Testfish4 <- Oto_lowres%>%filter(ID=="BH-01882")
Testfish5 <- Oto_lowres%>%filter(ID=="BH-01868")
Testfish6 <- Oto_lowres%>%filter(ID=="BH-01585")

P1 <- ggplot(Testfish1,aes(x=Sr, y=d18O))+
  geom_point()+
  labs(x="Sr/Ca (ppt)", y="d18O (permill)", 
       title="BH-90946, freshwater, likely anadromous")+
  ylim(-11,-3)+xlim(0,0.007)+
  theme_minimal()
P2 <- ggplot(Testfish2,aes(x=Sr, y=d18O))+
  geom_point()+
  labs(x="Sr/Ca (ppt)", y="d18O (permill)",
       title = "BH-91050, freshwater, likely anadromous")+
  ylim(-11,-3)+xlim(0,0.007)+
  theme_minimal()
P3 <- ggplot(Testfish3,aes(x=Sr, y=d18O))+
  geom_point()+
  labs(x="Sr/Ca (ppt)", y="d18O (permill)",
       title = "BH-90928, freshwater, likely anadromous")+
  ylim(-11,-3)+xlim(0,0.007)+
  theme_minimal()
P4 <- ggplot(Testfish4,aes(x=Sr, y=d18O))+
  geom_point()+
  labs(x="Sr/Ca (ppt)", y="d18O (permill)",
       title = "BH-01882, Bodden, likely resident")+
  ylim(-11,-3)+xlim(0,0.007)+
  theme_minimal()
P5 <- ggplot(Testfish5,aes(x=Sr, y=d18O))+
  geom_point()+
  labs(x="Sr/Ca (ppt)", y="d18O (permill)",
       title = "BH-01868, Bodden, likely resident")+
  ylim(-11,-3)+xlim(0,0.007)+
  theme_minimal()
P6 <- ggplot(Testfish6,aes(x=Sr, y=d18O))+
  geom_point()+
  labs(x="Sr/Ca (ppt)", y="d18O (permill)",
       title = "BH-01585, Bodden, likely resident")+
  ylim(-11,-3)+xlim(0,0.007)+
  theme_minimal()
ggarrange(P1,P2,P3,P4,P5,P6)

png(filename = "Figures/Correlation_d18O~Sr.png", 
    width = 3000, height = 1800, res = 600)
ggplot(Oto_lowres,aes(x=Sr*1000, y=d18O))+
  geom_point(size=.5)+
  scale_x_continuous(breaks = seq(0,8,1))+
  scale_y_continuous(breaks = seq(-15,0,1))+
  labs(x="Sr/Ca (mg/g)", 
       y=expression(bold(delta^18*"O"~("VPDB \u2030"))),
       title=expression(bold("Correlation of intraotolith Sr and"~delta^18*"O")))+
  stat_smooth(method = "lm", fullrange = T, size = .8)+
  theme_classic()+
    theme(panel.grid.major = element_line(),
          axis.line = element_line(size = .5, colour = "black", linetype = 1),
          axis.ticks = element_line(size = .5, colour = "black"),
          axis.text = element_text(size = 10, colour = "black"),
          axis.title.x = element_text(size = 10, face = "bold"),
          axis.title.y = element_text(size = 10, face = "bold"),
          legend.text = element_text(size = 5),
          legend.title = element_text(size = 10, face = "bold"),
          plot.title = element_text(size = 15, face = "bold", hjust = .5))
dev.off()
```

```{r add corrected d18O to data, include=FALSE, eval=FALSE}
#Get residuals from d18O ~ Sr
subset_KD <- subset(otoint_lowres, capt=="KD")
subset_KD$res <- NA
otoint_lowres <- otoint_lowres%>%drop_na()%>%filter(capt!="KD")%>%filter(ID!="BH-01908")

lm0 <- lm(d18O~1, data = otoint_lowres)
lm1 <- lm(d18O~Sr, data = otoint_lowres)
anova(lm0, lm1)
summary(lm1)

otoint_lowres$res <- lm1$residuals
otoint_lowres <- rbind(otoint_lowres, subset_KD)

#check for pattern retention
plot(otoint_lowres[otoint_lowres$ID=="BH-01889",]$sims_dist, otoint_lowres[otoint_lowres$ID=="BH-01889",]$res, type="l")
```

```{r average d18O residuals over years, include=FALSE, eval=FALSE}
#get d18O points per year to average over annual signal
otoint_lowres$year <- as.factor(otoint_lowres$year)

yearmean <- otoint_lowres%>%group_by(ID,year)%>%summarise(n=n())
mean(yearmean$n)
#mean of 7.6 so smooth with 7 or 8

otoint_lowres <- otoint_lowres%>%
  group_by(ID)%>%
  transmute(ID=ID,
            age=age,
            capt=capt,
            area=area,
            d18O=zoo::rollmean(d18O, k=7, fill = NA, align = "left"),
            res=zoo::rollmean(res, k=7, fill = NA, align = "left"),
            Sr=Sr,
            Na=Na,
            Mg=Mg,
            Ba=Ba,
            Mn=Mn,
            year=year,
            dist=sims_dist)

#check for pattern smoothness
plot(otoint_lowres[otoint_lowres$ID=="BH-01855",]$dist, otoint_lowres[otoint_lowres$ID=="BH-01855",]$d18O, type="l")

#Save data
write.table(otoint_lowres, "Data/Pike/Oto_LA-to-d18O_interpolation.txt", 
            row.names = F,dec = ".", sep = "\t")
```

## Lifelong niche on population level
```{r lifelong niche, include=FALSE}
#script to form annual means of elemental data for clustering and increment analysis
rm(list = ls())
#Read in data
otoint_lowres <- read.delim("Data/Pike/Oto_LA-to-d18O_interpolation.txt", header = T,
                            stringsAsFactors = F, dec = ".", sep = "\t")

otoint_lifehist <- otoint_lowres%>%
  transmute(ID=ID,
            age=as.factor(age),
            capt=capt,
            area=case_when(area=="WRB"~"Lagoon",
                           area=="NRB"~"Lagoon",
                           area=="Marine"~"Lagoon",
                           area=="Freshwater"~"Tributary"),
            d18O=d18O,
            d18O_res=res,
            Sr=Sr,
            year=as.factor(year),
            dist=dist)

# Plot lifelong increase in d18O --> colder the older
mypallette <- viridis::viridis(4, direction = 1)

d18O <- ggplot(otoint_lifehist, aes(year, d18O_res))+
  geom_boxplot(aes(color = area), width = 0.5, outlier.size = .5)+
  scale_x_discrete(limits = factor(1:10))+
  labs(x="Age (years)",
       y=expression(bold("Sr-corrected"~delta^18*"O"~("VPDB \u2030"))),
       color="area of capture")+
  theme_classic()+
  scale_color_viridis_d(direction = -1, begin = 0, end = 0.7)+
  theme(panel.grid.major = element_line(),
        legend.position = "none",
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        axis.line = element_line(size = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(size = .5, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title.x = element_text(size = 10, face = "bold"),
        axis.title.y = element_text(size = 10, face = "bold"),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10, face = "bold"),
        legend.key.size = unit(.8,"line"))

#Lifelong increase in Sr/Ca --> saltier the older
SrCa <- ggplot(otoint_lifehist, aes(year, Sr*1000))+
  geom_boxplot(aes(color = area), width = 0.5, outlier.size = .5)+
  scale_x_discrete(limits = factor(1:11))+
  labs(x="Age (years)",
       y="Sr/Ca (mg/g)",
       color="area of capture")+
  theme_classic()+
  scale_color_viridis_d(direction = -1, begin = 0, end = 0.7)+
  theme(panel.grid.major = element_line(),
        legend.position = "none",
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        axis.line = element_line(size = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(size = .5, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title.x = element_text(size = 10, face = "bold"),
        axis.title.y = element_text(size = 10, face = "bold"),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10, face = "bold"),
        legend.key.size = unit(.8,"line"))

png(filename = "Figures/Lifelong_niche.png", 
    width = 4500, height = 1800, res = 600)
ggarrange(d18O, SrCa, ncol = 2, nrow = 1, labels = c("A", "B"), common.legend = TRUE,
                legend = "bottom")
dev.off()
```


## Model-based preclustering
```{r preclustering prep, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
rm(list = ls())
#read in data
# oto_highres <- read.delim("Data/Otoliths/Oto_d18O-to-LA_interpolation.txt",
#                          header = T, dec = ".", sep = "\t",
#                          stringsAsFactors = F)
oto_lowres <- read.delim("Data/Pike/Oto_LA-to-d18O_interpolation.txt",
                         header = T, dec = ".", sep = "\t",
                         stringsAsFactors = F) #This is not low-res, you need to change that!!!

#Clustering step 1: model based clustering
#Form means
Elemeans <- oto_lowres%>%
  group_by(ID)%>%
  summarise(ID=ID,
            area=case_when(area=="WRB"~"Lagoon",
                           area=="NRB"~"Lagoon",
                           area=="Marine"~"Lagoon",
                           area=="Freshwater"~"Tributary",
                           area=="Control"~"Control lake"),
            Sr=mean(Sr),
            Na=mean(Na),
            Mg=mean(Mg),
            Ba=mean(Ba),
            Mn=mean(Mn),
            d18O=mean(d18O, na.rm=T))%>%
  distinct()

#Scale means
Elemeans[,3:8] <- scale(Elemeans[,3:8])
```

```{r preclustering, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
#Visual examination of distinction potential
X <- data.matrix(Elemeans[,3:8])
class <- factor(Elemeans$area)
table(class)
col <- mclust.options("classPlotColors")[1:3]

clp <- clPairs(X, class, lower.panel=NULL, gap=0, symbols = c(16,15,17),
               colors = adjustcolor(col, alpha.f = 0.5))
clPairsLegend(x = 0.1, y = 0.3, class = clp$class, col = col, 
              pch = clp$pch, title = "Capture location")

#model-based clustering with the most promising predictors (Sr & d18O)
fit <- Mclust(Elemeans[,c(3,8)])

#Evaluation plots
par(mar=c(5,5,1,1))
plot(fit, what = "BIC", xlab="Number of clusters", 
     legendArgs=list(x="topright", ncol=2, cex=0.5, inset=0.01),
     cex.lab=3)

par(mar=c(5,6,1,1))
plot(fit, what = "classification", 
     ylab=expression(delta^18*"O (normalized)"),
     xlab="Sr/Ca (normalized)", cex.lab=2, cex.axis=2, cex=2)

plot(fit, what = "uncertainty")
plot(fit, what = "density")
summary(fit, parameters=T)

#Cluster again with best method
fit2 <- Mclust(Elemeans[,c(3,8)], G=3, modelNames = "VII")

#Assign cluster to data
Elemeans$clust <- as.factor(fit2$classification)

#Make list of cluster & ID
ClustID <- Elemeans[,c(1,9)]
```

```{r plot preclustering results, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
#Plot cluster results
mypallette <- viridis::viridis(3, direction = 1)

png(filename = "Figures/Preclustering_results.png", 
    width = 3000, height = 1800, res = 600)
ggplot(Elemeans, aes(d18O, Sr, color=area, shape=clust))+
  labs(x=expression(bold(delta^18*"O (scaled)")), y="Sr/Ca (scaled)",
       shape="Cluster",
       title = "Preclustering results (VVI with 3 groups)")+
  geom_point(size=1)+
  theme_classic()+
  scale_color_manual(name="Capture location", 
                     breaks = c("Lagoon", "Tributary", "Control lake"),
                     values = mypallette)+
  theme(panel.grid.major = element_line(),
        axis.title = element_text(size = 10, face = "bold"), 
        axis.text = element_text(size = 10, colour = "black"),
        #legend.position = c(.85,.65),
        legend.text = element_text(size = 5),
        legend.title = element_text(size = , face = "bold"),
        legend.key.size = unit(.5,"line"),
        legend.background = element_blank(),
        legend.box.background = element_rect(),
        plot.title = element_text(size = 15, face = "bold"))
dev.off()
```

```{r subset data according to preclustering results, include=FALSE, eval=FALSE}

#Join cluster grouping to data
oto_clusters <- oto_lowres%>%
  inner_join(ClustID, by = "ID")%>%
  group_by(ID)%>%
  na.omit()%>%
  transmute(ID=ID,
            age=age,
            capt=capt,
            area=area,
            d18O=d18O,
            d18O_res=res,
            Sr=Sr,
            Na=Na,
            Mg=Mg,
            Ba=Ba,
            Mn=Mn,
            year=year,
            clust=clust,
            dist=dist)

#subset according to cluster
Fgroup <- subset(oto_clusters, clust==1)
Bgroup <- subset(oto_clusters, clust==2)

#Test length, needs to equal N=86
length(unique(Bgroup$ID))+length(unique(Fgroup$ID))

#Function to reinterpolate an element to a specified length
interpol <- function(series, length, element){
  ids <- NULL
  values <- NULL
  
  IDOto <- unique(series$ID)
  
  for (i in 1:length(IDOto)) {
    id <- rep(IDOto[i], length.out=length)
    value <- approx(series[which(series$ID==IDOto[i]), element],
                      method = "linear", n=length, rule = 2)[2]
    ids <- c(ids, id)
    values <- unlist(c(values, value))
    }
  
  data.frame(ID=ids, value=values)
  
}

#Test function
Srall <- interpol(series = oto_clusters, length = 250, element = "Sr")
d18Oall <- interpol(series = oto_clusters, length = 250, element = "d18O")

Srd18O <- cbind(Srall, d18Oall[,2])
colnames(Srd18O) <- c("ID", "Sr", "d18O")


#compare pattern retention
par(mfrow=c(1,2))
plot(oto_clusters[oto_clusters$ID=="BH-91045",]$dist,
     oto_clusters[oto_clusters$ID=="BH-91045",]$Sr, type="l",
     xlab="Distance (um)", ylab="Sr/Ca")
plot(row_number(Srd18O[Srd18O$ID=="BH-91045",]$ID),
     Srd18O[Srd18O$ID=="BH-91045",]$Sr, type="l",
     xlab="transect cell", ylab="Sr/Ca")

#data package
save(Fgroup,Bgroup,interpol, file = "Data/Pike/Adults_element_transects.RData")
```

## DTW-clustering
```{r get best clustering method?, include=FALSE, eval=FALSE}
rm(list = ls())
#read in data
Freshwater <- read.delim("Data/Otoliths/Freshwater-cluster.txt",
                         header = T, sep = "\t", dec = ".",
                         stringsAsFactors = F)

Bodden <- read.delim("Data/Otoliths/Bodden-cluster.txt",
                         header = T, sep = "\t", dec = ".",
                         stringsAsFactors = F)
Bodden <- Bodden%>%filter(ID!="BH-01908")

#make into list of matrices
IDOto <- unique(Bodden$ID)

series <- list()
for (i in 1:length(IDOto)) {
  m <- as.matrix(Bodden[which(Bodden$ID==IDOto[i]),c(5)])
  series[[length(series)+1]] <- m
}

names(series) <- c(IDOto)
labels <- NULL
Boddenlabels <- for (i in 1:length(IDOto)) {
  ind <- unique(Bodden[which(Bodden$ID==IDOto[i]), "area"])
  labels = c(labels, ind)
}

acf_fun <- function(series, ...) {
lapply(series, function(x) {
as.numeric(acf(x, lag.max = 50, plot = FALSE)$acf)
})
}


cfgs <- compare_clusterings_configs(
  types = c("h","t","f"),
  k = 2L,
  controls = list(hierarchical = hierarchical_control(method = "all"),
                tadpole = tadpole_control(dc = c(1.5,2), window.size = 5L),
                fuzzy = fuzzy_control(fuzziness = c(2,2.5),iter.max = 30L)
                ),
  preprocs = pdc_configs("preproc", none = list(),
                       zscore = list(center = c(FALSE)),
                       fuzzy = list(acf_fun=list()),
                       share.config = c("h", "t")
                       ),
  distances = pdc_configs("distance",
                        dtw=list(),fuzzy = list(L2 = list()),
                        share.config = c("h")
                        ),
  centroids = pdc_configs("centroid", hierarchical = list(default = list()),
                        fuzzy = list(fcmdd = list()),
                        tadpole = list(default = list(), 
                                       shape_extraction =list(znorm = TRUE)
                                       )
                        ),
  )

num_configs <- sapply(cfgs, attr, which = "num.configs")
cat("\nTotal number of configurations without considering optimizations:",
sum(num_configs),
"\n\n")


vi_evaluators <- cvi_evaluators("VI", ground.truth = labels)
score_fun <- vi_evaluators$score
pick_fun <- vi_evaluators$pick

comparison <- compare_clusterings(series, types = c("h", "t", "f"), configs = cfgs,
                                  trace = TRUE, seed = 293L, 
                                  score.clus = score_fun, pick.clus = pick_fun,
                                  return.objects = TRUE)
 #does not work yet... But unnecessary atm

```

```{r dtw data prep 3-year old, include=FALSE}
rm(list = ls())
#read in data
load("Data/Pike/Adults_element_transects.RData")

#Filter out vaterite fish, shorten to 3 year olds
Bgroup1 <- Bgroup%>%filter(ID!="BH-01908")%>%filter(age>=3, year<4)
Fgroup1 <- Fgroup%>%filter(age>=3, year<4)

#Look for sample size
length(unique(Bgroup1$ID))
length(unique(Fgroup1$ID))

#Mean transect length
summary(count(Bgroup1, "ID")) #Mean length 28 data points
summary(count(Fgroup1, "ID")) #Mean length 32 data points

#Make year a factor
Bgroup1$year <- as.factor(Bgroup1$year)
Fgroup1$year <- as.factor(Fgroup1$year)

#Calculate the number of transect cells needed to represent the "mean first"/"mean second"/
#"mean third" - year in standardized 30 cells interpolations
summary(Bgroup1$year)
year1 <- round((719/(719+446+243))*30,0)
year2 <- round((446/(719+446+243))*30,0)
year3 <- round((243/(719+446+243))*30,0)
year1+year2+year3 #needs to add up to 30

#reinterpolate to standard length
dataB1 <- interpol(series = Bgroup1, length = 30, element = "Sr")
dataB2 <- interpol(series = Bgroup1, length = 30, element = "d18O_res")

dataF1 <- interpol(series = Fgroup1, length = 30, element = "Sr")
dataF2 <- interpol(series = Fgroup1, length = 30, element = "d18O_res")

dataB <- cbind(dataB1, dataB2[,2])
dataF <- cbind(dataF1, dataF2[,2])

dataB[,2] <- scale(dataB[,2])
dataF[,2] <- scale(dataF[,2])

colnames(dataB) <- c("ID", "Sr", "d18O_res")
colnames(dataF) <- c("ID", "Sr", "d18O_res")

#make list of matrices for DTW
IDOto <- unique(dataB$ID)
Bseries <- list()

for (i in 1:length(IDOto)) {
  m <- as.matrix(dataB[which(dataB$ID==IDOto[i]),c(2,3)])
  Bseries[[length(Bseries)+1]] <- m
}

names(Bseries) <- c(IDOto)

IDOto <- unique(dataF$ID)
Fseries <- list()

for (i in 1:length(IDOto)) {
  m <- as.matrix(dataF[which(dataF$ID==IDOto[i]),c(2,3)])
  Fseries[[length(Fseries)+1]] <- m
}

names(Fseries) <- c(IDOto)

save(Fgroup,Bgroup,dataB, dataF, Bseries, Fseries, year1, year2, year3, interpol,
     file = "Data/Pike/Adults_element_transects.RData")
```

```{r DTW clustering 3 year olds}
#cluster Bodden with cutoff test
clust_B <- tsclust(series = Bseries, type = "hierarchical",
                  k = 2L:6L,centroid = dba,
                  control = hierarchical_control(method = "ward.D"),
                  seed = 94L,args = tsclust_args(dist = list(window.size =5L)))

names(clust_B) <- paste0("k_",2L:6L)

sapply(clust_B, cvi, type = "internal")

#cluster FW with cutoff test
clust_F <- tsclust(series = Fseries, type = "hierarchical",
                  k = 2L:6L,centroid = dba,
                  control = hierarchical_control(method = "ward.D"),
                  seed = 96L,args = tsclust_args(dist = list(window.size =5L)))

names(clust_F) <- paste0("k_",2L:6L)

sapply(clust_F, cvi, type = "internal")

#Plot best solution lagoons
# png(filename = "C:/Users/timor/Nextcloud2/Timo/BODDENHECHT/Chapter 2/Stats/Niche analysis/Figures/Year_3_Sr_d18O_centroids.jpg", width = 2400, height = 800)
plot(clust_B$k_2, type="centroid", linetype="solid", 
     alpha=0.5, cex=1)+
  ylim(-2.5,3)+ggtitle(expression("Sr/"~delta^18~O~"cluster centroids"))+
  labs(x="transect cell", y="scaled value")+
  theme(axis.text = element_text(size = 25, color="black"),
        axis.title = element_text(size = 25),
        plot.title = element_text(size = 25, hjust = 0.5))
#dev.off()

#Plot best solution Freshwater
plot(clust_F$k_2, type="centroid", linetype="solid", cex=1)+
  ylim(-2.5,2)+xlim(0,60)+ggtitle(expression("Sr/"~delta^18~O~"cluster centroids"))+
  labs(x="transect cell", y="scaled value")+
  theme(axis.text = element_text(size = 25, color="black"),
        axis.title = element_text(size = 25),
        plot.title = element_text(size = 25, hjust = 0.5))
```

```{r cluster assignment 3 year olds}
#assign clusters to fish
fishassign_B <- data.frame(ID=names(Bseries), 
                            clust2=factor(clust_B$k_2@cluster, 
                                           levels = c(1:2), 
                                           labels = c("High saline|warm",
                                                      "Low saline|cold")))

fishassign_F <- data.frame(ID=names(Fseries), 
                            clust2=factor(clust_F$k_2@cluster, 
                                           levels = c(1:2), 
                                           labels = c("FW low saline|cold",
                                                      "FW high saline|warm")))
#Join dtw clusters with pike data
Bgroup1$area <- ifelse(Bgroup1$area=="Marine", "GB", Bgroup1$area)

fishassign_B <- Bgroup1%>%
  group_by(ID)%>%
  transmute(ID=ID,
            capt=capt,
            area=as.factor(area),
            areaorder=case_when(area=="WRB"~1,
                                area=="NRB"~2,
                                area=="GB"~3,
                                area=="Freshwater"~4))%>%
  distinct()%>%
  inner_join(fishassign_B2, by="ID")%>%
  mutate(clust2=fct_relevel(clust2,
                             "Low saline|cold",
                             "High saline|warm"))

fishassign_F <- Fgroup1%>%
  group_by(ID)%>%
  transmute(ID=ID,
            capt=capt,
            area=area)%>%
  distinct()%>%
  inner_join(fishassign_F2, by="ID")%>%
  mutate(clust_O=fct_relevel(clust2,
                             "FW low saline|cold",
                             "FW high saline|warm"))
```

```{r plot Bodden proportions}
mypallette <- viridis::viridis(3, direction = -1)

#Plot Bodden proportions

#png(filename = "C:/Users/timor/Nextcloud2/Timo/BODDENHECHT/Chapter 2/Stats/Niche analysis/Figures/Clusterassign.jpg", width = 2400, height = 800)
ggplot(fishassign_B, aes(reorder(area.x, areaorder.x), fill=clust2))+
  geom_bar(position = "fill", width = .5)+theme_minimal()+
  labs(x="", y="proportion", fill="assigned cluster")+
  scale_fill_manual(breaks=c("Low saline|cold",
                             "High saline|warm"), 
                    values = mypallette)+
  theme(axis.text.y = element_text(size = 25, color = "black"),
        axis.text.x = element_text(size = 25, color = "black"),
        axis.title = element_text(size = 25),
        legend.text = element_text(size = 25),
        legend.title = element_text(size = 25),
        legend.position = "top")
#dev.off()

#Plot FW proportions
ggplot(fishassign_F, aes(capt, fill=clust2))+
  geom_bar(position = "fill", width = .5)+theme_minimal()+
  labs(x="", y="proportion", fill="assigned cluster")+
  scale_fill_manual(breaks=c("FW low saline|cold",
                             "FW high saline|warm"), 
                    values = mypallette)+
  theme(axis.text.y = element_text(size = 25, color = "black"),
        axis.text.x = element_text(size = 25, color = "black"),
        axis.title = element_text(size = 25),
        legend.text = element_text(size = 25),
        legend.title = element_text(size = 25),
        legend.position = "right")

write.table(fishassign_B, file = "Data/Pike/Year_3_Bclusters.txt", row.names = F,
            dec = ".", sep = "\t")
write.table(fishassign_F, file = "Data/Pike/Year_3_Fclusters.txt", row.names = F,
            dec = ".", sep = "\t")
```

```{r dissimilarity test, include=FALSE}
rm(list = ls())
#read in data
load("Data/Pike/Adults_element_transects.RData")

fishassign_B <- read.delim("Data/Pike/Year_3_Bclusters.txt", header = T,
                           stringsAsFactors = F, sep = "\t",dec=".")

fishassign_F <- read.delim("Data/Pike/Year_3_Fclusters.txt", header = T,
                           stringsAsFactors = F, sep = "\t",dec=".")

#transform data to all positive
dataB$d18O_res <- (dataB$d18O_res+sqrt((min(dataB$d18O_res))^2))
#So a value of d18O res is now to be interpreted as residual from predicted
#value + 2.518462

dataB$Sr <- (dataB$Sr+sqrt((min(dataB$Sr))^2))
#So a value of Sr is now to be interpreted as scaled value + 2.716513

#Same for reshwater group
dataF$d18O_res <- (dataF$d18O_res+sqrt((min(dataF$d18O_res))^2))
dataF$Sr <- (dataF$Sr+sqrt((min(dataF$Sr))^2))

#make list of matrices Bodden
IDOto <- unique(dataB$ID)
Bseries <- list()

for (i in 1:length(IDOto)) {
  m <- as.matrix(dataB[which(dataB$ID==IDOto[i]),c(2,3)])
  Bseries[[length(Bseries)+1]] <- m
}

names(Bseries) <- c(IDOto)

#make list of matrices freshwater
IDOto <- unique(dataF$ID)
Fseries <- list()

for (i in 1:length(IDOto)) {
  m <- as.matrix(dataF[which(dataF$ID==IDOto[i]),c(2,3)])
  Fseries[[length(Fseries)+1]] <- m
}

names(Fseries) <- c(IDOto)

#Revert from list to data frame, assign cell numbers
SeriesB <- do.call(rbind.data.frame,Bseries)
SeriesB$ID <- substr(rownames(SeriesB), 1,8)
rownames(SeriesB) <- NULL
SeriesB$cell <- rep(c(1:30), 50)

#Make cluster list
Bclust <- fishassign_B%>%
  transmute(ID=ID,
            clust=clust2)

#Assign years based on cell numbers, join with cluster ID
SeriesB <- SeriesB%>%
  mutate(year=case_when(cell<=year1~1,
                        cell<=year1+year2&cell>year1~2,
                        cell>year1+year2~3))%>%
  inner_join(Bclust, by="ID")%>%
  transmute(ID=ID,
            year=year,
            cell=cell,
            clust=clust,
            Sr=Sr,
            d18O_res=d18O_res)%>%
  group_by(ID, year)%>%
  summarize(ID=ID,
            year=year,
            clust=clust,
            Sr=mean(Sr),
            d18O_res=mean(d18O_res))%>%
  distinct()

#Make wide for testing
SeriesB2 <- pivot_wider(SeriesB, names_from = year, values_from = c(Sr, d18O_res))
names(SeriesB2) <- c("ID", "clust",
                    "Sr_orig", "Sr_juv", "Sr_adult", 
                    "O_orig", "O_juv", "O_adult")
#cluster needs to be a factor
SeriesB2$clust <- as.factor(SeriesB2$clust)

#make mvabund object of Sr and d18O data
elements <- mvabund(SeriesB2[,3:8])

boxplot(elements)

Pikedist <- vegdist(elements, method = "euclidean")
Disp <- betadisper(Pikedist, SeriesB2$clust)
anova(Disp)

plot(Disp)

adonis2(elements~SeriesB2$clust, method = "euclidean", permutations = 9999)
```

```{r jackknife reclassification 3 year olds}
set.seed(123)
sample <- sample(c(TRUE, FALSE), nrow(SeriesB2), 
                 replace = T, prob = c(0.6,0.4))
train <- SeriesB2[sample,]
test <- SeriesB2[!sample,]

lda.m1 <- lda(clust~Sr_orig+Sr_juv+Sr_adult+O_orig+O_juv+O_adult, 
              data = train)

#jackknife reclassification
lda.m2 <- lda(clust~Sr_orig+Sr_juv+Sr_adult+O_orig+O_juv+O_adult, 
              data = SeriesB2, CV=TRUE)

SeriesB2$jacknife <- lda.m2$class
SeriesB2 %>% summarise(lda.error=mean(clust != jacknife))
```

```{r dtw graphics}
Salcentroid <- DBA(Bseries[1:10], trace = T, mv.ver = "by-variable")
matplot(do.call(cbind, Bseries[1:10]), type = "l")
lines(Salcentroid)

data(uciCT)

# Obtain an average for the first 5 time series
dtw_avg <- DBA(CharTraj[1:5], trace = TRUE)

# Plot
matplot(do.call(cbind, CharTraj[1:5]), type = "l")
lines(dtw_avg)
```

## Setup and cleanup of data for mixed models

```{r LUNG cleanup for GLMM, include=FALSE, eval=FALSE}
# Script to read in and clean up LUNG data tables
rm(list = ls())

# Read in data
LUNGdata_coast <- read.delim("Data/Environment/Lungdata_all_coast_2005-2020.txt",
                             header = T, stringsAsFactors = F, 
                             sep = "\t", dec = ".")
LUNGdata_rivers <- read.delim("Data/Environment/Lungdata_all_rivers_2005-2020.txt",
                             header = T, stringsAsFactors = F, 
                             sep = "\t", dec = ".")

#Prepare data frames
LUNGdata_coast_clean <- LUNGdata_coast %>%
  transmute(id = MstNr,
            name = Messstelle,
            water_body = Gewässer,
            datetime = DATUM_Uhrzeit,
            parameter = Param_kurz,
            parameter2 = Parameter,
            value = WERT,
            unit = Einheit,
            depth = TIEFE,
            Lat = HW_GEO,
            Long = RW_GEO,
            turbidity = SICHTTIEFE,
            type = "Coast")

LUNGdata_rivers <- LUNGdata_rivers %>%
  transmute(id = MS_NR,
            name = Messstelle,
            water_body = Gewässer,
            datetime = DATUM_Uhrzeit,
            parameter = Param_kurz,
            parameter2 = Parameter,
            value = WERT,
            unit = Einheit,
            depth = NA,
            HW = HW,
            RW = RW,
            turbidity = NA)

# Convert from Gauß-Krueger to WGS84 coordinates--------------------------------
LUNGdata_rivers_GK <- data.frame(cbind(LUNGdata_rivers, "X_GK" = LUNGdata_rivers$RW,
                                       "Y_GK" = LUNGdata_rivers$HW))

coordinates(LUNGdata_rivers_GK) <- c("X_GK", "Y_GK")
proj4string(LUNGdata_rivers_GK) <- CRS("+init=epsg:5650")
LUNGdata_rivers_WGS84 <- spTransform(LUNGdata_rivers_GK, CRS("+init=epsg:4326"))

LUNGdata_rivers_WGS84 <- as.data.frame(LUNGdata_rivers_WGS84)

LUNGdata_rivers_clean <- LUNGdata_rivers_WGS84%>%
  transmute(id = id,
            name = name,
            water_body = water_body,
            datetime = datetime,
            parameter = parameter,
            parameter2 = parameter2,
            value = value,
            unit = unit,
            depth = depth,
            Lat = Y_GK,
            Long = X_GK,
            turbidity = turbidity, 
            type = "Freshwater")

# Filter for variables of interest before converting to wide and join-----------
LUNG_sal_temp_coast <- LUNGdata_coast_clean %>%
  filter(parameter == "W-T"|parameter2=="Wassertemperatur"|
           parameter == "SAL"|parameter2 == "Salzgehalt"|
           parameter == "P"|parameter2 == "Phophor, gesamt")%>%
  transmute(id = id,
            name = name,
            waterbody = water_body,
            date = lubridate::as_date(parse_date_time(datetime, orders = "ymd_HMS")),
            day = lubridate::day(parse_date_time(datetime, orders = "ymd_HMS")),
            month = lubridate::month(parse_date_time(datetime, orders = "ymd_HMS")),
            year = lubridate::year(parse_date_time(datetime, orders = "ymd_HMS")),
            parameter = parameter,
            value = value,
            depth = depth,
            Lat = Lat,
            Long = Long,
            turbidity = turbidity,
            measurement = "LUNG",
            type = type)

LUNG_sal_temp_rivers <- LUNGdata_rivers_clean %>%
  filter(parameter == "W-T"|parameter2=="Wassertemperatur"|
           parameter == "SAL"|parameter2 == "Salzgehalt"|
           parameter == "P"|parameter2 == "Phophor, gesamt")%>%
  transmute(id = id,
            name = name,
            waterbody = water_body,
            date = lubridate::as_date(parse_date_time(datetime, orders = "ymd_HMS")),
            day = lubridate::day(parse_date_time(datetime, orders = "ymd_HMS")),
            month = lubridate::month(parse_date_time(datetime, orders = "ymd_HMS")),
            year = lubridate::year(parse_date_time(datetime, orders = "ymd_HMS")),
            parameter = parameter,
            value = value,
            depth = depth,
            Lat = Lat,
            Long = Long,
            turbidity = turbidity,
            measurement = "LUNG",
            type = type)

#insert NAs for later means
LUNG_sal_temp_rivers <- LUNG_sal_temp_rivers%>%
  group_by(name, year, month, parameter)%>%
  summarize(id = id,
            name = name,
            waterbody = waterbody,
            month = month,
            year = year,
            parameter = parameter,
            value = mean(value, na.rm = T),
            Lat = Lat,
            Long = Long,
            turbidity=turbidity,
            measurement = measurement,
            type = type)%>%
  ungroup()%>%
  distinct()%>%
  pivot_wider(names_from = month, values_from = value)

LUNG_sal_temp_rivers <- LUNG_sal_temp_rivers%>%
  pivot_longer(cols = c(11:22), names_to = "month",
               values_to = "value", values_drop_na = F)

# remove double rows before converting to wide
LUNG_sal_temp_coast <- LUNG_sal_temp_coast[-c(11296, 11298, 563, 564),]

LUNG_sal_temp_coast <- LUNG_sal_temp_coast%>%
  group_by(name, year, month, parameter)%>%
  summarize(id = id,
            name = name,
            waterbody = waterbody,
            month = month,
            year = year,
            parameter = parameter,
            value = mean(value, na.rm = T),
            Lat = Lat,
            Long = Long,
            turbidity=turbidity,
            measurement = measurement,
            type = type)%>%
  ungroup()%>%
  distinct()%>%
  pivot_wider(names_from = month, values_from = value)

LUNG_sal_temp_coast <- LUNG_sal_temp_coast%>%
  pivot_longer(cols = c(11:22), names_to = "month",
               values_to = "value", values_drop_na = F)

# convert to wide
LUNG_sal_temp_coast <- spread(LUNG_sal_temp_coast, parameter, value)
head(LUNG_sal_temp_coast)
LUNG_sal_temp_rivers <- spread(LUNG_sal_temp_rivers, parameter, value)
head(LUNG_sal_temp_rivers)
LUNG_sal_temp_rivers$SAL <- 0

LUNGdata_all <- rbind(LUNG_sal_temp_coast, LUNG_sal_temp_rivers)
names(LUNGdata_all)[13] <- paste("WT")

# Add ID numbers
LUNGdata_all <- LUNGdata_all %>%
  transmute(id = case_when(name %in% "AW1 Trockenort" ~"0111030108",
                           waterbody %in% "Graben 44" ~"0103070022",
                           name %in% "DB6 Barth oe." ~"0103050603",
                           name %in% "DB2 Sundische Wiese" ~"0103050208",
                           name %in% "DB1 Pramort" ~"0103050101",
                           name %in% "GS Gellenstrom Hiddensee w." ~"0103070503",   
                           name %in% "RB2 Vitte oe." ~"0112190202",
                           name %in% "RB3 Bugspitze s." ~"0112190309",
                           name %in% "RB1 Schaprode w." ~"0112400185",
                           name %in% "KB90 Fahrwasser I.Libitz w." ~"0103059085",
                           name %in% "S66 Stralsund" ~"0109016609",
                           name %in% "RB6 Wittower Faehre oe." ~"0112280603",
                           name %in% "RB9 Glowe sw." ~"0112390909",
                           name %in% "RB10 Lietzow n." ~"0112391004",
                           name %in% "RB15 Buschvitz oe." ~"0112391500",
                           name %in% "GB3 Daenische Wiek n." ~"0105010306",
                           name %in% "GB2 I.Vilm s." ~"0105010285",
                           name %in% "GB19 Zentralbereich" ~"0105011907",
                           name %in% "GB7 Struck" ~"0105010701",
                           name %in% "GB10 Ruden s." ~"0111021001",
                           name %in% "O133 suedl. Greifsw. Oie" ~"0111071308",
                           name %in% "P20 Peenemuende s." ~"0111032085",
                           name %in% "P42 Wolgast s." ~"0111034208",
                           name %in% "P48 Lassan" ~"0111034806",
                           TRUE ~ id),
            name = name,
            waterbody = waterbody,
            #date = date,
            #day = day,
            month = month,
            year = year,
            #depth = depth,
            Lat = Lat,
            Long = Long,
            turbidity = turbidity,
            measurement = measurement,
            type = type,
            SAL = SAL,
            WT = WT,
            P=P)

#Must be zero:
unique(ifelse(is.na(LUNGdata_all$id)==T, 1, 0))

# join in 2021 data-------------------------------------------------------------

LUNGdata_coast_21 <- read.delim("Data/Environment/LUNG-Daten_all_coast_2021.txt",
                                header = T, stringsAsFactors = F, 
                                sep = "\t", dec = ".")
#clean
LUNGdata_coast_21 <- LUNGdata_coast_21 %>%
  transmute(id = paste0(0, PN.Stellennr.),
            date = lubridate::as_date(parse_date_time(Probenahmedatum, orders = "dmy_HM")),
            day = lubridate::day(parse_date_time(Probenahmedatum, orders = "dmy_HM")),
            month = lubridate::month(parse_date_time(Probenahmedatum, orders = "dmy_HM")),
            year = lubridate::year(parse_date_time(Probenahmedatum, orders = "dmy_HM")),
            depth = case_when(Tiefeninformation %in% "Grundnähe" ~ "bottom",
                              TRUE ~ "surface"),
            parameter = Parameter,
            value = Endergebnis)%>%
  filter(parameter == "Wassertemperatur"|
           parameter == "Salzgehalt"|
           parameter == "Gesamt P"|
           parameter == "Sichttiefe")

#insert NAs
LUNGdata_coast_21 <- LUNGdata_coast_21%>%
  group_by(id, year, month, parameter)%>%
  summarize(id = id,
            month = month,
            year = year,
            parameter = parameter,
            value = mean(as.numeric(value), na.rm = T))%>%
  ungroup()%>%
  distinct()%>%
  pivot_wider(names_from = month, values_from = value)

LUNGdata_coast_21 <- LUNGdata_coast_21%>%
  pivot_longer(cols = c(4:15), names_to = "month",
               values_to = "value", values_drop_na = F)

LUNGdata_coast_21 <- rbind(LUNGdata_coast_21[LUNGdata_coast_21$year!=2022,],
                           na.omit(LUNGdata_coast_21[LUNGdata_coast_21$year==2022,]))


#wide
LUNGdata_coast_21 <- spread(LUNGdata_coast_21, parameter, value)
head(LUNGdata_coast_21)

LUNGdata_coast_21 <- LUNGdata_coast_21 %>%
  transmute(id = id,
            #date = date,
            #day = day,
            month = month,
            year = year,
            #depth = depth,
            SAL = Salzgehalt,
            WT = Wassertemperatur,
            P_total=`Gesamt P`,
            trbidity=Sichttiefe)

# for loop to complement rows
IDstation <- unique(LUNGdata_coast_21$id)
df <- data.frame()
for (i in 1:length(IDstation)) {
  nm <- na.omit(unlist(ifelse(LUNGdata_coast_21$id == IDstation[i], 
              first(LUNGdata_all[which(LUNGdata_all$id == IDstation[i]), 
                                 "name"]), NA)))
  wb <- na.omit(unlist(ifelse(LUNGdata_coast_21$id == IDstation[i], 
              first(LUNGdata_all[which(LUNGdata_all$id == IDstation[i]),
                                 "waterbody"]), NA)))
  Lat <- na.omit(unlist(ifelse(LUNGdata_coast_21$id == IDstation[i], 
              first(LUNGdata_all[which(LUNGdata_all$id == IDstation[i]), "Lat"]), NA)))
  Long <- na.omit(unlist(ifelse(LUNGdata_coast_21$id == IDstation[i], 
              first(LUNGdata_all[which(LUNGdata_all$id == IDstation[i]), 
                                 "Long"]), NA)))
  df <- rbind(df, data.frame(nm, wb, Lat, Long))
}

#add missing columns
LUNGdata_coast_21 <- cbind(LUNGdata_coast_21, df)
#LUNGdata_coast_21$turbidity <- NA
LUNGdata_coast_21$type <- "Coast"
LUNGdata_coast_21$measurement <- "LUNG"

LUNGdata_coast_21 <- LUNGdata_coast_21 %>%
  transmute(id = id,
            name = nm,
            waterbody = wb,
            #date = date,
            #day = day,
            month = month,
            year = year,
            #depth = depth,
            Lat = Lat,
            Long = Long,
            turbidity = trbidity,
            measurement = measurement,
            type = type,
            SAL = SAL,
            WT = WT,
            P=P_total)

LUNGdata_all <- data.frame(rbind(LUNGdata_all, LUNGdata_coast_21))

LUNGdata_all <- LUNGdata_all%>%
  transmute(waterbody = case_when(name %in% "AW1 Trockenort" ~"P",
                                  name %in% "DB1 Pramort" ~"BAT",
                                  name %in% "DB10 Bodstedt n." ~"BoB",
                                  name %in% "DB16 Saal nw." ~"SaB",
                                  name %in% "DB2 Sundische Wiese" ~"BAT",
                                  name %in% "DB6 Barth oe." ~"BAT",
                                  name %in% "GB10 Ruden s." ~"GB",
                                  name %in% "GB19 Zentralbereich" ~"GB",
                                  name %in% "GB2 I.Vilm s." ~"GB",
                                  name %in% "GB3 Daenische Wiek n." ~"GB",
                                  name %in% "GB7 Struck" ~"GB",
                                  name %in% "GS Gellenstrom Hiddensee w." 
                                  ~"Baltic",
                                  name %in% "KB90 Fahrwasser I.Libitz w." ~"WRB",
                                  name %in% "O133 suedl. Greifsw. Oie" ~"Baltic",
                                  name %in% "P20 Peenemuende s." ~"P",
                                  name %in% "P42 Wolgast s." ~"P",
                                  name %in% "P48 Lassan" ~"P",
                                  name %in% "RB1 Schaprode w." ~"WRB",
                                  name %in% "RB10 Lietzow n." ~"NRB",
                                  name %in% "RB15 Buschvitz oe." ~"KJB",
                                  name %in% "RB2 Vitte oe." ~"WRB",
                                  name %in% "RB3 Bugspitze s." ~"NRB",
                                  name %in% "RB6 Wittower Faehre oe." ~"NRB",
                                  name %in% "RB9 Glowe sw."~"NRB",
                                  name %in% "S66 Stralsund" ~"WRB",
                                  name %in% "Barth" ~"Barthe",
                                  name %in% "Klein Damitz" ~"Bandycksgraben",
                                  name %in% "Wolgast" ~"Ziese",
                                  name %in% "Neuendorf" ~"Sehrowbach",
                                  name %in% "Kemnitz" ~"Ziese",
                                  TRUE~name),
            id = id,
            name = name,
            month = month,
            year = year,
            Lat = Lat,
            Long = Long,
            turbidity = turbidity,
            measurement = measurement,
            type = type,
            SAL = SAL,
            WT = WT,
            P=P)

Lungdata <- LUNGdata_all%>%
  group_by(waterbody, year)%>%
  summarise(type=type,
            turbidity=mean(turbidity, na.rm=T),
            SAL=mean(SAL, na.rm=T),
            WT=mean(WT, na.rm=T),
            P=mean(P, na.rm=T))%>%
  distinct()

# save file
write.table(Lungdata, 
            file = "Data/LUNGdata.txt", 
            sep = "\t", dec = ".", row.names = F)


```

```{r shape data, include=FALSE, eval=FALSE}
#Script to read cleaned environmental data and combine it with pike data
rm(list = ls())

Lungdata <- read.delim("Data/Environment/LUNGdata.txt", header = T, 
                       stringsAsFactors = F, sep = "\t", dec = ".")

pikedat_B <- read.delim("Data/Pike/Growthdata_Bodden-cluster.txt", 
                        sep = "\t", dec = ".", header = T, stringsAsFactors = F)

pikedat_F <- read.delim("Data/Pike/Growthdata_Freshwater-cluster.txt", 
                        sep = "\t", dec = ".", header = T, stringsAsFactors = F)

#Clean up data frames
pikedata_B <- pikedat_B%>%
  transmute(ID=as.character(ID),
            area=area,
            capt=capt,
            clust=as.factor(paste0("S_",clust)),
            age=as.integer(age),
            cohort=as.integer(cohort),
            weight=weigth,
            TL=as.numeric(TL),
            sex=as.factor(sex),
            lifeyear=factor(i, levels = c(1:13), labels = c(1:13)),
            year=year,
            inc=as.numeric(increment),
            rad=as.numeric(rad))

pikedata_F <- pikedat_F%>%
  transmute(ID=as.character(ID),
            area=area,
            capt=capt,
            clust=as.factor(paste0("F_",clust)),
            age=as.integer(age),
            cohort=as.integer(cohort),
            weight=weigth,
            TL=as.numeric(TL),
            sex=as.factor(sex),
            lifeyear=factor(i, levels = c(1:13), labels = c(1:13)),
            year=year,
            inc=as.numeric(increment),
            rad=as.numeric(rad))
#Bind together
pikedata <- rbind(pikedata_B, pikedata_F)

oto_lowres <- read.delim("Data/Pike/Oto_LA-to-d18O_interpolation.txt",
                         header = T, dec = ".", sep = "\t",
                         stringsAsFactors = F)

oto_years <- oto_lowres%>%
  group_by(ID,year)%>%
  summarise(ID=ID,
            lifeyear=as.factor(year),
            d18O_mean=mean(d18O),
            res_mean=mean(res),
            Sr_mean=mean(Sr),
            d18O_min=min(d18O),
            res_min=min(res),
            Sr_min=min(Sr),
            d18O_max=max(d18O),
            res_max=max(res),
            Sr_max=max(Sr))

pikedata <- pikedata%>%inner_join(oto_years, by=c("ID", "lifeyear"))%>%
  transmute(ID=ID,
            waterbody=area,
            capt=capt,
            clust=clust,
            age=age,
            cohort=cohort,
            weight=weight,
            TL=TL,
            sex=sex,
            lifeyear=lifeyear,
            year=year.x,
            inc=inc,
            rad=rad,
            d18O_mean=d18O_mean,
            d18O_max=d18O_max,
            d18O_min=d18O_min,
            res_mean=res_mean,
            res_max=res_max,
            res_min=res_min,
            Sr_mean=Sr_mean,
            Sr_max=Sr_max,
            Sr_min=Sr_min)%>%
  drop_na(inc,rad,year)%>%
  distinct()

pikedata <- pikedata%>%left_join(Lungdata, by=c("waterbody", "year"))

write.table(pikedata, 
            file = "Data/Pikedata.txt", 
            sep = "\t", dec = ".", row.names = F)
```

## Prepare data for modelling

```{r project start, include=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
rm(list = ls())

pikes <- read.delim("Data/Pike/Pikedata.txt", header = T, stringsAsFactors = F,
                    sep = "\t", dec = ".")
head(pikes)
tail(pikes)
str(pikes)

#Prepare data frame with factors and scale+center element data
pikes2 <- pikes%>%
  transmute(ID=ID,
            waterbody=factor(waterbody),
            clust=as.factor(clust),
            sex=as.factor(sex),
            lifeyear=lifeyear,
            inc=inc,
            res_mean=as.numeric(scale(res_mean)),
            Sr_mean=as.numeric(scale(Sr_mean)),
            visibility=as.numeric(scale(turbidity)),
            Sal=as.numeric(scale(SAL)),
            WT=as.numeric(scale(WT)),
            P=as.numeric(scale(P)))
#Check
str(pikes2)
```

## Data exploration

```{r Exploration, include=FALSE, echo=FALSE, fig.height=6, fig.width=8}
#Exploration

par(mfrow=c(1,2))
dotchart(pikes2$inc, color = pikes2$clust, main = "Color = Ecotype(Cluster)")
dotchart(pikes2$inc, color = pikes2$sex, main = "Color = Sex")
```

```{r Exploration, include=FALSE, echo=FALSE, fig.height=5, fig.width=8}
par(mfrow=c(3,2))
boxplot(pikes2$inc~pikes2$lifeyear, ylab ="Growth increment", xlab = "Age")
boxplot(pikes2$inc~pikes2$clust, ylab ="Growth increment", xlab = "Ecotype")
boxplot(pikes2$inc~pikes2$sex, ylab ="Growth increment", xlab = "Sex")
plot(pikes2$inc~pikes2$res_mean, ylab ="Growth increment", xlab = "d18O")
plot(pikes2$inc~pikes2$Sr_mean, ylab ="Growth increment", xlab = "Sr")
plot(0, xaxt = 'n', yaxt = 'n', bty = 'n', pch = '', ylab = '', xlab = '')
```

```{r Exploration, include=FALSE, echo=FALSE, fig.height=5, fig.width=8}
par(mfrow = c(2,2))
hist(pikes2$inc, main = "", xlab = "Increment (um)")
hist(pikes2$res_mean, main = "", xlab = "d18O ratio")
hist(pikes2$Sr_mean, main = "", xlab = "Sr concentration")
plot(0, xaxt = 'n', yaxt = 'n', bty = 'n', pch = '', ylab = '', xlab = '')

```

## Initial model
$$log10(Inc) \sim Age*cluster+Age*d18Ores+Srmean+turbidity+salinity+WT+P+Sex+(1|Loc/ID)$$

```{r exclude random effect of ID}
#Run model
pikemodel.1 <- lmer(log10(inc)~lifeyear*res_mean+lifeyear*clust+I(lifeyear^2)+
                        Sr_mean+sex+(1|waterbody/ID), 
                      REML = T, data = pikes2)
summary(pikemodel.1)
#Random effects cannot be estimated as too low variance
#Model runs properly when excluding ID:
pikemodel.1.0 <- lmer(log10(inc)~lifeyear*res_mean+lifeyear*clust+I(lifeyear^2)+
                      Sr_mean+sex+(1|waterbody), 
                      REML = T, data = pikes2)
summary(pikemodel.1.0)
```
 
## New model
$$log10(Inc) \sim Age*d18Ores+Age*cluster+Age^2+Srmean+Sex+(1|Location)$$

```{r Look at variance inflation factors, echo=TRUE}
#Look at variance inflation factors
pikemodel.1.0 <- lmer(log10(inc)~lifeyear*res_mean+lifeyear*clust+I(lifeyear^2)+
                      Sr_mean+sex+(1|waterbody), 
                      REML = T, data = pikes2)

pike.vif <- vif(pikemodel.1.0)

barplot(pike.vif[,3], main = "VIF values", horiz = F, col = "darkgreen", ylim = c(0,6),
        las = 2)
abline(h = 5, lwd = 3, lty = 2, col="red")
```

## Log-likelihood ratio tests
```{r test random effects, echo=TRUE}
#Test model components
#Test random effects
rand(pikemodel.1.0)

summary(pikemodel.final)
```

```{r test effects age, echo=TRUE}
#Remove age quadratic term
pikemodel.1.0 <- lmer(log10(inc)~lifeyear*res_mean+lifeyear*clust+I(lifeyear^2)+
                      Sr_mean+sex+(1|waterbody), 
                      REML = F, data = pikes2)

pikemodel.noage <- lmer(log10(inc)~lifeyear*res_mean+lifeyear*clust+
                      Sr_mean+sex+(1|waterbody), 
                      REML = F, data = pikes2)

anova(pikemodel.1.0, pikemodel.noage)
#age is significant
```

```{r test cluster effects}
pikemodel.noclust <- lmer(log10(inc)~lifeyear*res_mean+clust+I(lifeyear^2)+
                      Sr_mean+sex+(1|waterbody), 
                      REML = F, data = pikes2)
anova(pikemodel.1.0, pikemodel.noclust)
#age*cluster is significant
```

```{r test effects d18O, echo=TRUE}
#Remove d18O
pikemodel.nores <- lmer(log10(inc)~lifeyear*clust+res_mean+I(lifeyear^2)+
                      Sr_mean+sex+(1|waterbody), 
                      REML = F, data = pikes2)
anova(pikemodel.1.0, pikemodel.nores)
#relative d18O significant
```

```{r test effects Sr, echo=TRUE}
#Remove Sr
pikemodel.noSr <- lmer(log10(inc)~lifeyear*res_mean+lifeyear*clust+I(lifeyear^2)+
                      sex+(1|waterbody), 
                      REML = F, data = pikes2)
anova(pikemodel.1.0, pikemodel.noSr)
#Sr not significant
```

```{r test effects sex, echo=TRUE}
#Remove sex
pikemodel.nosex <- lmer(log10(inc)~lifeyear*res_mean+lifeyear*clust+I(lifeyear^2)+
                      Sr_mean+(1|waterbody), 
                      REML = F, data = pikes2)
anova(pikemodel.1.0, pikemodel.nosex)
#sex is significant
```

## Results
```{r table, out.width="120%", dpi=300, echo=FALSE, message=FALSE}
summary(pikemodel.final)
tab_model(pikemodel.final, show.fstat = T, show.loglik = T, digits.re = 20)
```

## Model validation
```{r model validation, echo=FALSE}
#validation
pikemodel.final <- lmer(log10(inc)~lifeyear*res_mean+lifeyear*clust+I(lifeyear^2)+
                      Sr_mean+sex+(1|waterbody), 
                      REML = T, data = pikes2)

pikes2$resid <- resid(pikemodel.final)

plot(pikemodel.final, xlab = "Fitted", ylab = "Residuals")
hist(pikes2$resid, main = "", xlab = "Residuals")

qqnorm(resid(pikemodel.final))
qqline(resid(pikemodel.final))


plot(pikes2$resid~pikes2$clust, ylab = "Residuals", xlab = "Cluster", las = 2)
plot(pikes2$resid~pikes2$sex, ylab = "Residuals", xlab = "Sex")
plot(pikes2$resid~pikes2$lifeyear, ylab = "Residuals", xlab = "Age")
plot(pikes2$resid~pikes2$res_mean, ylab = "Residuals", xlab = "d18O")
plot(pikes2$resid~pikes2$Sr_mean, ylab = "Residuals", xlab = "Sr concentration")

r.squaredGLMM(pikemodel.final)
```

## Figure main effects
```{r temp & clust effect figure}
#factorize temperature
pikes2$agefact <- ifelse(pikes2$lifeyear<3, 2, 
                         ifelse(pikes2$lifeyear>2&pikes2$lifeyear<7, 1,
                                ifelse(pikes2$lifeyear>6, 3, NA)))

pikes2$agefact2 <- factor(pikes2$agefact,levels = c(2,1,3),
                                            labels = c("juvenile", "adult", "trophy"))

#rename clusters
pikes3 <- pikes2%>%
  mutate(clust2=case_when(clust=="F_HighS"~3,
                          clust=="F_IntS"~3,
                          clust=="F_LowS"~1,
                          clust=="S_HighS"~2,
                          clust=="S_IntS"~4,
                          clust=="S_LowS"~4))
pikes3$clust <- factor(pikes3$clust2,
                       levels = c(1,2,3,4),
                       labels = c("Freshwater resident/stable temperature", 
                                  "Brackish resident/stable temperature",
                                  "Anadromous/thermal shift",
                                  "Semianadromous/thermal shift"))

mypallette <- viridis::viridis(4, direction = 1)

#Temperature effect
Temp <- ggplot(pikes2, aes(res_mean, inc, color=agefact2))+
  geom_point(size=.5)+
  stat_smooth(method = "lm", fill="gray", fullrange = T, lwd=.8)+
  labs(x=expression(bold("scaled"~delta^18*"O"~("Sr-corrected, VPDB \u2030"))), 
       y=expression(bold("increment"~(mu*"m"))),
       color="ageclass")+
  scale_color_viridis_d()+
  theme_classic()+
  theme(panel.grid.major = element_line(),
        legend.position = c(.803,.825),
        legend.background = element_blank(),
        legend.box.background = element_rect(),
        axis.line = element_line(size = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(size = .5, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title.x = element_text(size = 10, face = "bold"),
        axis.title.y = element_text(size = 10, face = "bold"),
        legend.text = element_text(size = 5),
        legend.title = element_text(size = 10, face = "bold"),
        legend.key.size = unit(.8,"line"))

#Cluster effect
Clust <- ggplot(pikes3[pikes$lifeyear<=10,], aes(factor(lifeyear), inc, color=clust))+
  geom_boxplot(lwd=.3, outlier.size = .5)+
  labs(x="Age (years)", y=expression(bold("increment"~(mu*"m"))), color="ecotype")+
  scale_x_discrete(breaks=c("1","2","3","4","5","6","7","8","9","10"))+
  scale_color_manual(breaks = c("Freshwater resident/stable temperature", 
                                  "Brackish resident/stable temperature",
                                  "Anadromous/thermal shift",
                                  "Semianadromous/thermal shift"),
                     values = mypallette)+
  theme_classic()+
  theme(panel.grid.major = element_line(),
        legend.position = c(.715,.79),
        legend.background = element_blank(),
        legend.box.background = element_rect(),
        axis.line = element_line(size = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(size = .5, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 10, face = "bold"),
        axis.title.y = element_blank(),
        legend.text = element_text(size = 5),
        legend.title = element_text(size = 10, face = "bold"),
        legend.key.size = unit(.8,"line"))

Fig <- ggarrange(Temp, Clust, align = "h", labels = c("A", "B"), label.x = .02)+
  theme(plot.margin = margin(.5,0,0,0,"cm"))

png(filename = "Figures/Interaction_effects_growth.png", 
    width = 4500, height = 2000, res = 600)
annotate_figure(Fig, top = text_grob("Effects of relative lifelong temperature and ecotype on pike growth", color = "black", face = "bold", size = 15, vjust = 1))
dev.off()
```
